### ISSUE TITLE
When scrolling the side navigation, Flutter throws `Error: The provided ScrollController is currently attached to more than one ScrollPosition.`

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#154]
## Description
When scrolling with a large device in the side navigation, Flutter throws the following error:
```
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.
The Scrollbar requires a single ScrollPosition in order to be painted.
When the scrollbar is interactive, the associated Scrollable widgets must have unique
ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
packages/flutter/src/widgets/scrollbar.dart 1333:9                                <fn>
packages/flutter/src/widgets/scrollbar.dart 1356:14                               [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1272:14                               [_validateInteractions]
packages/flutter/src/animation/listener_helpers.dart 233:27                       notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 815:7                    [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 749:5                    [_startSimulation]
packages/flutter/src/animation/animation_controller.dart 612:12                   [_animateToInternal]
packages/flutter/src/animation/animation_controller.dart 461:12                   forward
packages/flutter/src/widgets/scrollbar.dart 1642:46                               [_handleScrollNotification]
packages/flutter/src/widgets/notification_listener.dart 151:27                    [_dispatch]
packages/flutter/src/widgets/notification_listener.dart 67:19                     visitAncestor
packages/flutter/src/widgets/scroll_notification.dart 31:18                       visitAncestor
packages/flutter/src/widgets/framework.dart 4254:39                               visitAncestorElements
packages/flutter/src/widgets/notification_listener.dart 83:13                     dispatch
packages/flutter/src/widgets/scroll_activity.dart 94:90                           dispatchScrollUpdateNotification
packages/flutter/src/widgets/scroll_position.dart 900:5                           didUpdateScrollPositionBy
packages/flutter/src/widgets/scroll_position_with_single_context.dart 221:7       pointerScroll
packages/flutter/src/widgets/scrollable.dart 717:16                               [_handlePointerScroll]
packages/flutter/src/gestures/pointer_signal_resolver.dart 88:7                   resolve
packages/flutter/src/gestures/binding.dart 445:29                                 handleEvent
packages/flutter/src/gestures/binding.dart 419:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 322:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                                 [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1026:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 184:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 130:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 295:14                                    [_handleWheelEvent]
lib/_engine/engine/pointer_binding.dart 559:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 284:84                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall

The AnimationController notifying status listeners was:
  AnimationController#f4e77(▶ 0.000)
════════════════════════════════════════════════════════════════════════════════════════════════════
Error: The provided ScrollController is currently attached to more than one ScrollPosition.
The Scrollbar requires a single ScrollPosition in order to be painted.
When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a
Scrollable widget.
    at Object.throw_ [as throw] (http://localhost:61294/dart_sdk.js:5391:11)
    at http://localhost:61294/packages/flutter/src/widgets/widget_inspector.dart.lib.js:32903:25
    at scrollbar$0._MaterialScrollbarState.new.[_debugCheckHasValidScrollPosition]
    (http://localhost:61294/packages/flutter/src/widgets/widget_inspector.dart.lib.js:32908:28)
    at scrollbar$0._MaterialScrollbarState.new.[_validateInteractions]
    (http://localhost:61294/packages/flutter/src/widgets/widget_inspector.dart.lib.js:32871:67)
    at animation_controller.AnimationController.new.notifyStatusListeners
    (http://localhost:61294/packages/flutter/src/animation/listener_helpers.dart.lib.js:255:69)
    at animation_controller.AnimationController.new.[_checkStatusChanged]
    (http://localhost:61294/packages/flutter/src/animation/animation_controller.dart.lib.js:515:14)
    at animation_controller.AnimationController.new.[_startSimulation]
    (http://localhost:61294/packages/flutter/src/animation/animation_controller.dart.lib.js:487:32)
    at animation_controller.AnimationController.new.[_animateToInternal]
    (http://localhost:61294/packages/flutter/src/animation/animation_controller.dart.lib.js:406:36)
    at animation_controller.AnimationController.new.forward (http://localhost:61294/packages/flutter/src/animation/animation_controller.dart.lib.js:315:38)
    at scrollbar$0._MaterialScrollbarState.new.[_handleScrollNotification]
    (http://localhost:61294/packages/flutter/src/widgets/widget_inspector.dart.lib.js:33155:217)
    at NotificationListener.new.[_dispatch] (http://localhost:61294/packages/flutter/src/widgets/widget_inspector.dart.lib.js:50206:59)
    at scroll_notification.ScrollUpdateNotification.new.visitAncestor
    (http://localhost:61294/packages/flutter/src/widgets/widget_inspector.dart.lib.js:35545:46)
    at scroll_notification.ScrollUpdateNotification.new.visitAncestor
    (http://localhost:61294/packages/flutter/src/widgets/widget_inspector.dart.lib.js:48337:20)
    at framework.StatefulElement.new.visitAncestorElements (http://localhost:61294/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25983:44)
    at scroll_notification.ScrollUpdateNotification.new.dispatch (http://localhost:61294/packages/flutter/src/widgets/widget_inspector.dart.lib.js:35553:32)
    at scroll_activity.IdleScrollActivity.new.dispatchScrollUpdateNotification
```

## Demo
https://user-images.githubusercontent.com/24459435/164995149-4241d455-1541-4550-90e6-e3c566e799bc.mov

**Comment by nilsreichardt** [comment]
This ticket can be a blocking ticket for desktop integration tickets. So adding it to the "Integration testing" project.
