### ISSUE TITLE
Error when running `sz license-headers add`: `Unhandled exception: Exception: The process exited with a non-zero code (1)`

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#360]
## Describe the bug

```
Nils-MBP-13-M1-3:sz_repo_cli nils$ sz license-headers add
Unhandled exception:
Exception: The process exited with a non-zero code (1)

2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/DKPhotoGallery/DKPhotoGallery/DKPhotoIncrementalIndicator.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/DKPhotoGallery/DKPhotoGallery/DKPhotoIncrementalIndicator.swift: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/PDFPreview/DKPhotoPDFPreviewVC.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/PDFPreview/DKPhotoPDFPreviewVC.swift: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/PDFPreview/DKPDFView.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/PDFPreview/DKPDFView.swift: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/FMDB/src/fmdb/FMDB.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/FMDB/src/fmdb/FMDB.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/FMDB/src/fmdb/FMResultSet.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/FMDB/src/fmdb/FMResultSet.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/FMDB/src/fmdb/FMDatabase.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/FMDB/src/fmdb/FMDatabase.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/FMDB/src/fmdb/FMDatabase.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/FMDB/src/fmdb/FMDatabase.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/FMDB/src/fmdb/FMResultSet.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/FMDB/src/fmdb/FMResultSet.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/GoogleSignIn/.cocoapods.yml: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/GoogleSignIn/.cocoapods.yml: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/GoogleMLKit/MLKitCore/Sources/MLKit.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/GoogleMLKit/MLKitCore/Sources/MLKit.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/MTBBarcodeScanner/Classes/ios/Scanners/MTBBarcodeScanner.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBAny.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBAny.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBAny.pbobjc.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBAny.pbobjc.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBApi.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBApi.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBApi.pbobjc.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBApi.pbobjc.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBDuration.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBDuration.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBSourceContext.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBSourceContext.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBTimestamp.pbobjc.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBTimestamp.pbobjc.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBDuration.pbobjc.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBDuration.pbobjc.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBStruct.pbobjc.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBStruct.pbobjc.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBType.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBType.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBStruct.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBStruct.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBTimestamp.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBTimestamp.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBSourceContext.pbobjc.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBSourceContext.pbobjc.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBEmpty.pbobjc.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBEmpty.pbobjc.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBEmpty.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBEmpty.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBFieldMask.pbobjc.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBFieldMask.pbobjc.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBFieldMask.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBFieldMask.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBType.pbobjc.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBType.pbobjc.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Duration.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Duration.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Api.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Api.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Empty.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Empty.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/FieldMask.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/FieldMask.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Type.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Type.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Timestamp.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Timestamp.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Wrappers.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Wrappers.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/SourceContext.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/SourceContext.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Struct.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Struct.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBWrappers.pbobjc.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBWrappers.pbobjc.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBWrappers.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/GPBWrappers.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Any.pbobjc.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Protobuf/objectivec/google/protobuf/Any.pbobjc.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/PurchasesCoreSwift/PurchasesCoreSwift/Networking/ETagManager.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/PurchasesCoreSwift/PurchasesCoreSwift/Networking/ETagManager.swift: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Purchases/Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/Purchases/Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/PurchasesCoreSwift/PurchasesCoreSwift/SubscriberAttributes/AttributionKey.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/PurchasesCoreSwift/PurchasesCoreSwift/SubscriberAttributes/AttributionKey.swift: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/SwiftyGifManager.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/SwiftyGifManager.swift: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SDWebImageWebPCoder/SDWebImageWebPCoder/Classes/SDWebImageWebPCoderDefine.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SDWebImageWebPCoder/SDWebImageWebPCoder/Classes/SDWebImageWebPCoderDefine.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/ObjcAssociatedWeakObject.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/ObjcAssociatedWeakObject.swift: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/NSImageView+SwiftyGif.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/NSImageView+SwiftyGif.swift: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/UIImage+SwiftyGif.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/UIImage+SwiftyGif.swift: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/NSImage+SwiftyGif.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/NSImage+SwiftyGif.swift: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/UIImageView+SwiftyGif.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/SwiftyGif/SwiftyGif/UIImageView+SwiftyGif.swift: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_common.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_common.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_common.c: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_common.c: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_decode.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_decode.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_encode.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_encode.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_encode.c: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_encode.c: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_decode.c: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/ios/Pods/nanopb/pb_decode.c: permission denied
2023/02/22 19:39:04 skipping: /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Flutter/GeneratedPluginRegistrant.swift
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/FMDB/src/fmdb/FMDB.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/FMDB/src/fmdb/FMDB.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/FMDB/src/fmdb/FMResultSet.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/FMDB/src/fmdb/FMResultSet.h: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/FMDB/src/fmdb/FMResultSet.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/FMDB/src/fmdb/FMResultSet.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/FMDB/src/fmdb/FMDatabase.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/FMDB/src/fmdb/FMDatabase.m: permission denied
2023/02/22 19:39:04 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/FMDB/src/fmdb/FMDatabase.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/FMDB/src/fmdb/FMDatabase.h: permission denied
2023/02/22 19:39:05 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/Purchases/Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.m: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/Purchases/Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.m: permission denied
2023/02/22 19:39:05 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/PurchasesCoreSwift/PurchasesCoreSwift/SubscriberAttributes/AttributionKey.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/PurchasesCoreSwift/PurchasesCoreSwift/SubscriberAttributes/AttributionKey.swift: permission denied
2023/02/22 19:39:05 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/PurchasesCoreSwift/PurchasesCoreSwift/Networking/ETagManager.swift: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/PurchasesCoreSwift/PurchasesCoreSwift/Networking/ETagManager.swift: permission denied
2023/02/22 19:39:05 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_common.c: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_common.c: permission denied
2023/02/22 19:39:05 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_common.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_common.h: permission denied
2023/02/22 19:39:05 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_decode.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_decode.h: permission denied
2023/02/22 19:39:05 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_encode.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_encode.h: permission denied
2023/02/22 19:39:05 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb.h: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb.h: permission denied
2023/02/22 19:39:05 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_encode.c: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_encode.c: permission denied
2023/02/22 19:39:05 /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_decode.c: open /Users/nils/Desktop/Projects/sharezone/sharezone-app/app/macos/Pods/nanopb/pb_decode.c: permission denied
2023/02/22 19:39:05 skipping: /Users/nils/Desktop/Projects/sharezone/sharezone-app/lib/abgabe/abgabe_http_api/lib/model/datei_hinzufuegen_command_dto.g.dart
2023/02/22 19:39:05 skipping: /Users/nils/Desktop/Projects/sharezone/sharezone-app/lib/abgabe/abgabe_http_api/lib/model/datei_hinzufuegen_command_dto1.g.dart
2023/02/22 19:39:05 skipping: /Users/nils/Desktop/Projects/sharezone/sharezone-app/lib/abgabe/abgabe_http_api/lib/model/dateien_hinzufuegen_command_dto.g.dart
2023/02/22 19:39:05 skipping: /Users/nils/Desktop/Projects/sharezone/sharezone-app/lib/abgabe/abgabe_http_api/lib/model/dateiname_dto.g.dart
2023/02/22 19:39:05 skipping: /Users/nils/Desktop/Projects/sharezone/sharezone-app/lib/abgabe/abgabe_http_api/lib/model/inline_response400.g.dart
2023/02/22 19:39:05 skipping: /Users/nils/Desktop/Projects/sharezone/sharezone-app/lib/abgabe/abgabe_http_api/lib/model/inline_response403.g.dart
2023/02/22 19:39:05 skipping: /Users/nils/Desktop/Projects/sharezone/sharezone-app/lib/abgabe/abgabe_http_api/lib/model/submission_dto.g.dart
2023/02/22 19:39:05 skipping: /Users/nils/Desktop/Projects/sharezone/sharezone-app/lib/abgabe/abgabe_http_api/lib/serializers.g.dart
2023/02/22 19:39:05 skipping: /Users/nils/Desktop/Projects/sharezone/sharezone-app/lib/holidays/lib/src/api/holiday.g.dart
2023/02/22 19:39:05 skipping: /Users/nils/Desktop/Projects/sharezone/sharezone-app/lib/holidays/lib/src/api/serializers.g.dart

#0      AddLicenseHeadersCommand.run (package:sz_repo_cli/src/commands/src/add_license_headers_command.dart:38:7)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#2      main.<anonymous closure> (package:sz_repo_cli/src/main.dart:48:12)
<asynchronous suspension>
```

**Comment by nilsreichardt** [comment]
@Jonas-Sander Maybe it's because of `permission denied` errors. Ignoring the Pods directories might the fix for this and in general in a good idea
