### ISSUE TITLE
Error when running `sz analyze`: `Could not find a file named "pubspec.yaml" in "/Users/nils/.pub-cache/hosted/pub.dev/fvm-2.4.1".`

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#364]
## Describe the bug

When running `sz analyze`, I'm getting this error:

```
NilsMBP13M13:sharezone-app nils$ sz analyze
Activating tuneup package...
Unhandled exception:
Exception: Process ended with non-zero exit code: fvm dart pub global activate tuneup (exit code 66): Can't load Kernel binary: Invalid SDK hash.
Could not find a file named "pubspec.yaml" in "/Users/nils/.pub-cache/hosted/pub.dev/fvm-2.4.1".


 stdout:
#0      runProcessSucessfullyOrThrow (package:sz_repo_cli/src/common/src/run_process.dart:34:5)
<asynchronous suspension>
#1      AnalyzeCommand.run (package:sz_repo_cli/src/commands/src/analyze_command.dart:45:5)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#3      main.<anonymous closure> (package:sz_repo_cli/src/main.dart:48:12)
<asynchronous suspension>
```

**Comment by nilsreichardt** [comment]
Running `dart pub global activate fvm` fixed it 👍
