### ISSUE TITLE
Integration tests sometimes fail because of `[firebase_messaging/unknown] java.io.IOException: AUTHENTICATION_FAILED`

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#420]
https://github.com/SharezoneApp/sharezone-app/actions/runs/4352511936/jobs/7605384172

```
❌ Authentication User should be able to sign in (failed)
  ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
  The following FirebaseException was thrown running a test:
  [firebase_messaging/unknown] java.io.IOException: AUTHENTICATION_FAILED
  
  When the exception was thrown, this was the stack:
  #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
  #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
  <asynchronous suspension>
  <asynchronous suspension>
  (elided one frame from package:stack_trace)
  
  The test description was:
    User should be able to sign in
```

I think this happens because Firebase Messaging is blocked on devices which are used by many developers.

**Comment by nilsreichardt** [comment]
Releated issue:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
  The following FirebaseException was thrown running a test:
  [firebase_messaging/unknown] java.io.IOException: SERVICE_NOT_AVAILABLE
  
  When the exception was thrown, this was the stack:
  #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
  #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
  <asynchronous suspension>
  <asynchronous suspension>
  (elided one frame from package:stack_trace)
  
  The test description was:
    User should be able to sign in
  ════════════════════════════════════════════════════════════════════════════════════════════════════
  Test failed. See exception logs above.
  The test description was: User should be able to sign in
```
