### ISSUE TITLE
Timetable does not when device language is Arabic

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#903]
## Demo

![image](https://github.com/SharezoneApp/sharezone-app/assets/24459435/735cc5ef-5019-45f4-87f3-4734ebae56d2)

## Steps to reproduce

1. Use Android Emulator
2. Set language to Arabic
3. Open timetable

**Comment by nilsreichardt** [comment]
<img width="456" alt="image" src="https://github.com/SharezoneApp/sharezone-app/assets/24459435/6911148d-3bd5-4e19-8f59-3981967314e8">

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following FormatException was thrown building TimetablePeriodView(dirty):
Invalid radix-10 number (at character 1)
٠٠
^

The relevant error-causing widget was
TimetablePeriodView
timetable_week_view.dart:66
When the exception was thrown, this was the stack
#0      int._handleFormatError (dart:core-patch/integers_patch.dart:126:5)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:137:16)
#2      int._parse (dart:core-patch/integers_patch.dart:98:12)
#3      int.parse (dart:core-patch/integers_patch.dart:60:12)
#4      Time.hour
time.dart:43
#5      Time.totalMinutes
time.dart:54
#6      Time.isBefore
time.dart:91
#7      Period.includesTime
period.dart:80
#8      Periods.isCloseToAnyPeriod
period.dart:221
#9      TimetablePeriodView.build
timetable_time_view.dart:43
#10     StatelessElement.build
framework.dart:5367
#11     ComponentElement.performRebuild
framework.dart:5297
#12     Element.rebuild
framework.dart:5016
#13     ComponentElement._firstBuild
framework.dart:5279
#14     ComponentElement.mount
framework.dart:5273
#15     Element.inflateWidget
framework.dart:4182
#16     MultiChildRenderObjectElement.inflateWidget
framework.dart:6569
```
