### ISSUE TITLE
Can't open email program via change account type dialog.

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#99]
## Describe the bug
When selecting the "contact support" option on the change account type dialog on Android the email program does not open (should open with predefined text).

## Steps to Reproduce
1. Go to Settings ("Einstellungen") > My account ("Mein Konto")
2. Tap onto account type ("Account-Type") tile
3. Tap "contact support" ("Support kontaktieren") button in the dialog

## Current _broken_ behavior
Nothing happens on Android

## Expected behavior
The email program should open with a predefined email template.

## Screenshots, videos or logs
![image](https://user-images.githubusercontent.com/29028262/151872857-c60f737e-73de-46e5-bc7e-3bc224b326bd.png)

## Tested device
 - Device: Pixel 4a
 - OS: Android 12
- App version: 1.6.1 (315)

## Additional context
```
I/UrlLauncher(16600): component name for mailto:support@sharezone.net?subject=Typ+des+Accounts+%C3%A4ndern+%5BJZ4jMkAgetSwMafFDEWBGr4IYuB2%5D is {com.google.android.gm/com.google.android.gm.ComposeActivityGmailExternal}
E/MethodChannel#plugins.flutter.io/url_launcher(16600): Failed to handle method call
E/MethodChannel#plugins.flutter.io/url_launcher(16600): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onLaunch(MethodCallHandlerImpl.java:88)
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:40)
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#plugins.flutter.io/url_launcher(16600): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (16600): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/flutter (16600): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onLaunch(MethodCallHandlerImpl.java:88)
E/flutter (16600): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:40)
E/flutter (16600): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (16600): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (16600): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (16600): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (16600): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (16600): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (16600): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (16600): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (16600): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (16600): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (16600): )
E/flutter (16600): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter (16600): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (16600): <asynchronous suspension>
E/flutter (16600): #2      launch
package:url_launcher/url_launcher.dart:101
E/flutter (16600): <asynchronous suspension>
E/flutter (16600):
```

**Comment by nilsreichardt** [comment]
This feature doesn't exist in the app anymore.
